### PR TITLE
Add OAuth authentication

### PR DESCRIPTION
**Pull request by phillychris**
I'm new to node and not great at Javascript, so please review. If you have questions you can find me on News Nerdery slack at @enactdev

I originally got this working by adding files to dist/ and consulting your auth.js file, [Google's Quickstart for sheets & node](https://developers.google.com/sheets/api/quickstart/nodejs) and the repository for [Google Auth Library](https://github.com/googleapis/google-auth-library-nodejs). 

Once it was working in the dist/ directory I added everything to the src/ directory and ran:

```
./node_modules/.bin/babel  src --out-dir dist --copy-file
```

Based on the build command in `package.json`.  I did not commit all changes that were created by the build command, only what was touched by my code. So the following were left out: 

 * dist/common/auth.js
 * dist/docs/test.js
 * dist/drive/test.js
 * dist/parse/test.js
 * dist/sheets/test.js
 * package-lock.json

### CODE REVIEW

**Comment by brizandrew** [comment]
Hey Chris,

Thanks for contributing! I think this is definitely a really good authentication alternative to the service accounts I released this library with. I wonder though if in the spirit of this library we can't make it a little more simple for users.

If I'm understanding this correctly, the function you've written needs a `credentials.json` file and a `token.json` file. The credentials are downloaded by clicking the button in that example link you sent posted and the token is gotten by running that piece of node code which prompts users to authenticate themselves to retrieve a token. Does that sound correct? 

If so I think we may be able to make an easy CLI that has the equivalent of the `getNewToken` function in the Google example.

Besides that, I also think if we have multiple `auth` strategies we should make auth another family. So that users call `goot.auth.oauth()` or `goot.auth.serviceAccount()`. That's an easy enough change that I can throw in once we've agreed on the discussion above.

**Comment by phillychris** [comment]
Yes, you understand that correctly. Good ideas, I was thinking of incorporating something from `getNewToken` but wanted to get the initial thing working first. I started working on a gulp task to create `token.json.` Should be able to wrap that up pretty quickly tomorrow.

**Comment by brizandrew** [comment]
If you can just get me the code that you would hypothetically run in a gulp task, I'm happy to make a quick setup CLI. 

Just something that takes some credentials and generates a token.json file. Maybe if we just take a path to a `credentials.json` file and it creates a `token.json` file in that same location? I can help with that too if you'd like.

I figure that way we can keep it agnostic and people can use whatever task runner (gulp, grunt, npm scripts, etc) they want with it or just run an easy `gootenberg setup` command if it's installed globally

**Comment by phillychris** [comment]
This is almost working, but it doesn't wait for the prompt. It just exists. I'm still figuring out the async / await workflow. 

```
import Gootenberg from 'gootenberg';
import { OAuth2Client } from 'google-auth-library';
import credentials from './credentials.json'
const fs = require('fs');
const readline = require('readline');

const SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly'];

const TOKEN_PATH = 'token.json';


async function createOAuthToken() {
    const goot = new Gootenberg();
    //console.log('Hi Chris')
    const {client_secret, client_id, redirect_uris} = credentials.installed;

    var client = new OAuth2Client(client_id, client_secret, redirect_uris[0]);

    const authUrl = client.generateAuthUrl({
      access_type: 'offline',
      scope: SCOPES,
    });
    console.log('Authorize this app by visiting this url:', authUrl);
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    rl.question('Enter the code from that page here: ', (code) => {
      rl.close();
      client.getToken(code, (err, token) => {
        if (err) return console.error('Error while trying to retrieve access token', err);
        client.setCredentials(token);
        // Store the token to disk for later program executions
        fs.writeFile(TOKEN_PATH, JSON.stringify(token), (err) => {
          if (err) return console.error(err);
          console.log('Token stored to', TOKEN_PATH);
        });
      });
    });

}

exports.createOAuthToken = createOAuthToken;
```

**Comment by brizandrew** [comment]
Okay I made the CLI and merged this in with a few changes. Thanks for contributing! Looks like it's working on my end!

**Pull request merged**
